name: Build Kivy APK (Debug)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-dev \
                                  zip unzip git libglib2.0-0 libsdl2-dev \
                                  libavformat-dev libavcodec-dev libavdevice-dev \
                                  libavutil-dev libswscale-dev libswresample-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build debug APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sherin-debug-apk
          path: bin/*.apk
